### ISSUE TITLE
Diff coverage should be a PR requirement

### ISSUE THREAD

**Issue by displague** [linode/linodego#100]
In https://github.com/linode/linodego/pull/89#issuecomment-548014411, there are currently no tests being added for new code.  The overall project coverage drops by 1.5% but the diff (new code) includes 0% test coverage.

All PRs should require some level of test coverage.  Project maintainers can always override these limitations and force a merge.

**Comment by phillc** [comment]
Hello,
We are trying to increase the level of test coverage across the codebase. However, for the time being, this will remain a social enforcement. Hopefully we can pull our % upwards.
