### ISSUE TITLE
Consider documenting linodego alongside the API|CLI documentation

### ISSUE THREAD

**Issue by DazWilkin** [linode/linodego#109]
It would be helpful if linodego's Types and methods were documented alongside the (good) API|CLI documentation:

E.g. Account

https://developers.linode.com/api/v4/account

complemented by:
https://github.com/linode/linodego/blob/master/account.go

This may encourage broader adoption and perhaps greater consistency between the SDK and API

**Comment by phillc** [comment]
Have you seen the godoc?

https://godoc.org/github.com/linode/linodego

**Comment by DazWilkin** [comment]
Yes.

I'm suggesting a mapping more than creation of documentation.

For example:
https://developers.linode.com/api/v4/account

REST: https://api.linode.com/v4/account
CLI: `linode-cli account view`

I can then visit the godoc and find:

https://godoc.org/github.com/linode/linodego#Client.GetAccount
https://godoc.org/github.com/linode/linodego#Account

But it would be helpful if this content were merged into the API documentation so that it could be viewed in one place, without inferring the mapping and being able to (more) quickly determine that there's a discrepancy: the API includes e.g. `balance_uninvoiced` but this is not yet part of the SDK (#108)

Potentially you could then auto-generate snippets for the call or bundle sample code.

I'm a former Googler and biased but the APIs and SDKs is one area of Google's documentation that is exemplary (and mostly) auto-generated too:
https://cloud.google.com/compute/docs/reference/rest/beta/instances/list

This shows 
+ the API, the method, request and response types;
+ Access to the API through Google APIs Explorer
+ Examples (bottom of page) for each of the SDK languages

What's missing also with Google's documentation is the direct link to the e.g. godoc for Golang.

**Comment by bbiggerr** [comment]
Closing this out — while we see the value of this request, it's not currently feasible to maintain separate documentation (other than https://godoc.org/github.com/linode/linodego) for this client as we do with our API and CLI, which are generated together through OpenAPI. We developed LinodeGo with a custom API through necessity, as there wasn't (and currently isn't) an acceptable OpenAPI equivalent.
