### ISSUE TITLE
Add a generic `WaitFor` that can handle status or event based waiting

### ISSUE THREAD

**Issue by displague** [linode/linodego#15]
Add a generic `WaitFor` that can handle status or event based waiting. This should allow for concurrency when performing actions on different Linodes, as the Linode API only blocks against actions on the same Linode.

At the very least, this issue could be addressed with Linode, Image, Snapshot, and BlockStorage status polling helpers.

Also add README and godoc instructions on how to use this (and the WaitForEventFinished) feature.

**Comment by phillc** [comment]
Hello,

I think this already exists. Regardless, terraform would likely be a consumer of this if it was necessary, and perhaps the use case of waiting for things is already handled.

**Comment by displague** [comment]
The thinking with this issue was that a single `WaitFor` that would channel all awaited resources.  This would consolidate the polling calls to share a common requeue timer for rate limiting concerns.

(Consider this pseudo-code, and not necessarily the best interface)
```go
instanceA:=&linodego.Instance{ID: 1234}
backup:=&linodego.InstanceBackup{LinodeID: instanceA.ID, ID: 5678}

waiter:=&linodego.NewWaitQueue{}
waiter.WaitFor(instance, func(obj interface{}) bool { return obj.(*linodego.Instance).Status == linodego.InstanceStatusReady } )
waiter.WaitFor(backup, func(obj interface{}) bool { return obj.(*linodego.InstanceBackup).Status == linodego.BackupStatusAvailable } )

instanceB:=&linodego.Instance{ID: 9876}
waiter.WaitFor(instanceB, func(obj interface{}) bool { return obj.(*linodego.Instance).Status == linodego.InstanceStatusReady } )

for {
  obj, done := waiter.Wait() // chan(interface{}), chan(bool)
  if done {break}
  swith obj:=obj.(type) {
   case *linodego.Instance:
    fmt.Println("Instance ready", obj.ID, obj.Status)
    if (instanceA.ID == obj.ID) { *instanceA = *obj}
    if (instanceB.ID == obj.ID) { *instanceB = *obj}
   case *linodego.InstanceBackup:
      fmt.Println("Backup ready", obj.ID, obj.Status)
  }
}
```

The `WaitFor` function would be able to pool together, into a single Linode list call, the poll for instanceA and instanceB. This takes advantage of the list filter parameters to 'OR' several requests together.

Additionally, any 429 responses (or header messages from 200s or 404s offering rate limiting advice) could be applied to all polls since they would be consolidated through the waiter.

The WaitFor function could be more case optimized, taking known IDs and Status values as fields, perhaps as helpers (`waiter.WaitForInstanceStatus(id, status)`).

Some more context was offered here https://github.com/linode/linodego/pull/89#issuecomment-511004458 with the approach that @jnschaeffer offered with futures.
