### ISSUE TITLE
Remove dependency on k8s.io/client-go

### ISSUE THREAD

**Issue by tamalsaha** [linode/linodego#155]
## General:

* [x] Have you removed all sensitive information, including but not limited to access keys and passwords?
* [x] Have you checked to ensure there aren't other open or closed [Pull Requests](../../pulls) for the same bug/feature/question?

----

We would like to see linodego remove its dependency on `k8s.io/client-go` package here: https://github.com/linode/linodego/tree/master/internal/kubernetes

This causes problem as users may depend on a different version of k8s.io/client-go. And k8s.io/client-go breaks its compatibility every 3 months.

Proposed Solution:
Please expose that package as its own Go module. You can do that keeping that package in this git repo or in separate repos.

**Comment by phillc** [comment]
Hello,

Thank you for your input! This is a valid criticism.

We plan on doing a batch of backwards incompatible changes in the near future, and will try to address this at that time.

Thanks!

**Comment by zechenbit** [comment]
Yes, it would be great if we can remove the dependencies from k8s.io.

By introducing this SDK, I ran into some kind of dependency problem: https://github.com/inlets/inlets-operator/pull/83#discussion_r449778266
