### ISSUE TITLE
Consider refactoring WaitForEventFinished "seen" filter optimization

### ISSUE THREAD

**Issue by danovotny** [linode/linodego#159]
### General:
When using the [Linode Terraform Provider](https://github.com/linode/terraform-provider-linode), I would intermittently get boot and disk errors while specifying an explicit disk configuration for my instance.

On the Terraform side, this manifests in errors like:
`Error booting Linode instance xxxxxxxx: [002] Get "https://api.linode.com/v4/account/events?page=1": context deadline exceeded`
`Error waiting for Linode instance xxxxxxxx disk: [002] Get "https://api.linode.com/v4/account/events?page=1": context deadline exceeded`

Digging through this code a bit I came across the comment added in [Pull Request #76](https://github.com/linode/linodego/pull/76/files#diff-18dc188a67872bccb91f231d01326eecR174)
```go
		// With potentially 1000+ events coming back, we should filter on something
		// Warning: This optimization has the potential to break if users are clearing
		// events before we see them.
		"seen": false,
```

While Terraform was running, I was actively working in the Linode Manager and clicking on the notification bell icon to follow along with the progress. After finding that comment in the code, I finally realized that reading the notification events was causing the errors. If I run the Terraform without clicking on the notification bell icon, the instance will then be successfully created.

I am not sure what possible options there might be for refactoring the "seen" filter optimization, but I wanted to at least open an issue incase others run in to the same errors I was seeing.

### Expected Behavior:
The Linode Terraform Provider (linodego) can be used while also using the Linode Manager and viewing notification events (the bell icon).

### Actual Behavior:
Viewing notification events in the Linode Manager (the bell icon) can cause the Linode Terraform Provider (linodego) to error while waiting for events.

### Steps to Reproduce the Problem:
1. Start an API call that utilizes `WaitForEventFinished`
1. View notification events in the Linode Manager (the bell icon)
1. API call will timeout

### Environment Specifications
macOS: 10.14.6
Terraform: 0.13.0
Linode Terraform Provider: 1.12.4

**Comment by LBGarber** [comment]
Closing because the `seen` optimization has been removed in https://github.com/linode/linodego/pull/215.

**Comment by danovotny** [comment]
Thank you! 🎉
