### ISSUE TITLE
go modules: retract v1.0.0

### ISSUE THREAD

**Issue by ldez** [linode/linodego#183]
## General:

* [x] Have you removed all sensitive information, including but not limited to access keys and passwords?
* [x] Have you checked to ensure there aren't other open or closed [Pull Requests](../../pulls) for the same bug/feature/question?

----

## Bug Reporting

When you will update your minimal version to go 1.16

https://github.com/linode/linodego/blob/bb01a08d7dc77b97a8fe2d66bd8f6ae4b722b252/go.mod#L9

Could you add the following `retract` directives:

```go
retract (
    v1.0.0 // add explanation
)
```

- https://blog.golang.org/go116-module-changes#TOC_5.
- https://golang.org/ref/mod#go-mod-file-retract

Thank you.

**Comment by phillc** [comment]
Great suggestion. Thank you.
