### ISSUE TITLE
Please retract v1.0.0

### ISSUE THREAD

**Issue by roidelapluie** [linode/linodego#204]
1.0.0 has been published one year ago, then retracted from github.

To avoid downstream users to use it, it is needed to publish a v1.0.1 with the following in the go.mod:

```
retract [v1.0.0, v1.0.1]
```

See: https://play-with-go.dev/retract-module-versions_go116_en/

**Comment by LBGarber** [comment]
Hello!
Now that we have released v1.1.0, v1.0.0 has been properly retracted.
