### ISSUE TITLE
consider putting resources in their own packages

### ISSUE THREAD

**Issue by displague** [linode/linodego#33]
An API consumer may not want to import eveything linodego offers if they are only concerned with DNS.

Consider how each of these CRUD resources could implement a common interface and register themselves with the client.

The base client could implement the current interface of providing all the CRUD functions for every request, but consumers of the API wouldn't be forced to use that client (does this mean moving the client into a separate package too?)

**Comment by phillc** [comment]
Hello,

This has aged quite a bit. The chances are that if we introduce breaking changes, that we would make sweeping changes across the entire codebase at the same time. I too strongly desire splitting the codebase into many packages, but this is unlikely to happen in the short term.
