### ISSUE TITLE
Implement API 4.0.4 changes (mostly SSH Key support)

### ISSUE THREAD

**Issue by displague** [linode/linodego#47]
Per https://developers.linode.com/changelog

- [x] Add profile_sshkeys.go, profile_sshkeys_test.go (use template.go)
  - [x] Revise RebuildInstance and InstanceRebuildOptions
  - [x] Revise CreateInstance and InstanceCreateOptions
  - [x] Revise CreateDisk and InstanceDiskCreateOptions
- [x] Implement RebuildNodebalancerConfig
- [x] Revise CreateNodebalancer for fast-track config settings (from v4.0.2)

**Comment by cliedeman** [comment]
Started on CreateNodebalancer and RebuildNodebalancerConfig in #48
