### ISSUE TITLE
[Help]: Using access key + secret key

### ISSUE THREAD

**Issue by ivasylenko** [linode/linodego#489]
### Description

I am currently using PAT, but looking for a way to switch to access keys.
Trying to understand if this is something I can achieve with linodego or need to do something else

**Comment by yec-akamai** [comment]
Hi @ivasylenko, 

Thank you for reaching out. Currently the Linode API only supports authentication using Personal Access tokens and OAuth tokens. Access and secret keys are generally reserved for accessing Object Storage buckets via the S3 API, which you can access using the AWS Go SDK's s3 package: https://docs.aws.amazon.com/sdk-for-go/api/service/s3/

**Comment by zliang-akamai** [comment]
You may also use newer [AWS SDK for Go v2](https://aws.github.io/aws-sdk-go-v2/docs/getting-started/#invoke-an-operation) or another open-source S3 client like [MinIO Go client](https://github.com/minio/minio-go), which are more compact and lighter than AWS SDK for Go v1.

**Comment by ykim-1** [comment]
Hey @ivasylenko , closing this issue for now but do reach out if you need additional help following @yec-akamai 's comment above.
