### ISSUE TITLE
client.ListNotifications() panics

### ISSUE THREAD

**Issue by dradtke** [linode/linodego#67]
It looks like the notifications endpoint is [not currently defined as a resource](https://github.com/linode/linodego/blob/9f8d0fc73c373cb5dcb65c670afc53b118fe9bdd/client.go#L190-L221). The line where the panic actually occurs is [here](https://github.com/linode/linodego/blob/9f8d0fc73c373cb5dcb65c670afc53b118fe9bdd/account_notifications.go#L39).

**Comment by displague** [comment]
@dradtke,

Thanks for opening this issue and pinpointing the reason!  I think you were looking for `ListEvents` (as it relates to status polling for the packer images), but I'm grateful that you found this.

This auto-closed when I merged the fix branch into master.  I'll release this with a tag in the next few days/week.

Can you try you use-case against the master branch?
