### ISSUE TITLE
Not possible to disable AllowAutoDiskResize in type InstanceResizeOptions struct

### ISSUE THREAD

**Issue by ellisbenjamin** [linode/linodego#86]
In instances.go, line 154-170

```
// InstanceResizeOptions
type InstanceResizeOptions struct {
	Type string `json:"type"`

	// When enabled, an instance resize will also resize a data disk if the instance has no more than one data disk and one swap disk
	AllowAutoDiskResize bool `json:"allow_auto_disk_resize,omitempty"`
}
```

Since AllowAutoDiskResize is a bool, assigning this a false value will result in the field registering as empty, and then being omitted. Since the API defaults to allowing automatic disk resizing, this makes it impossible to disable automatic disk resizing.

@jnschaeffer

**Comment by displague** [comment]
It looks like that should have been `*bool` to honor the Linode default of `true`, so only explicit overrides would be submitted (via `omitempty`).

**Comment by jnschaeffer** [comment]
I was thinking `*bool` could work, with the caveat that it puts users at risk of nil pointer derefs elsewhere. That said, if it's what we use elsewhere in linodego, I'd be more in favor of consistency over keeping users from doing something bad. In the future (or the present) we could use something like `sql.Null{Bool,Float64,Int64,String}` and be done with it.

**Comment by jnschaeffer** [comment]
@ellisbenjamin This is fixed now, right?

**Comment by ellisbenjamin** [comment]
Yes it is, many thanks @jnschaeffer 

closing.
